# Site settings
title: 风之城美国代购网
keywords: 美国代购, 化妆品, 营养品, 衣服, COACH包, MK, Michael Kors包, Kipling包, bag, handbag
email: 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://atjshop.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
encoding: utf-8
exclude: [obj/, processing/, vs-html.v12.suo, vs-html.sln, atjshop.csproj.user, atjshop.csproj, vs-html.suo, npp.workspace]

